[environment_variables]
POSTGRES_USER = "postgres"
POSTGRES_PASSWORD = "postgres"
POSTGRES_HOST = "postgres"
POSTGRES_DB = "postgres"
POSTGRES_PORT = 5432
ADMIN_USER = "admin"
ADMIN_PASSWORD = "admin"
ADMIN_EMAIL = "admin@example.com"
