# Generated by Django 5.1.4 on 2024-12-27 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='ipaddress',
            field=models.GenericIPAddressField(null=True),
        ),
        migrations.AddField(
            model_name='choice',
            name='user_id',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='user_id',
            field=models.BigIntegerField(default=0),
        ),
    ]
