# Generated by Django 4.2.7 on 2023-12-05 01:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_category_comment_post_remove_choice_question_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='comment_dislikes',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='comment_likes',
        ),
        migrations.RemoveField(
            model_name='post',
            name='post_content',
        ),
        migrations.RemoveField(
            model_name='post',
            name='post_dislikes',
        ),
        migrations.RemoveField(
            model_name='post',
            name='post_likes',
        ),
        migrations.AddField(
            model_name='post',
            name='pub_state',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('like_status', models.BooleanField(default=True)),
                ('like_author', models.CharField(max_length=200)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('like_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.post')),
            ],
        ),
        migrations.CreateModel(
            name='Commend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commend_status', models.BooleanField(default=True)),
                ('commend_author', models.CharField(max_length=200)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('commend_comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.comment')),
            ],
        ),
    ]
