openapi: 3.0.0
info:
  title: h plus spotrts api
  version: 1.0.0
tags:
  - name: Article
    description: Articles for for sport
paths:
  /product/{productId}:
    get:
      parameters:
        - in: path
          name: productId
          required: true
          schema:
            type: integer
            example: 1234
        - in: header
          name: customer-security-header
          required: false
          schema:
            type: integer
            example: 1234-4322-312
      responses:
        200:
          description: This is a list of products in the catalog
          content:
            application/json:
              schema:
                  $ref: '#/components/schemas/Product'
  /product:
    post:
      description: Add a product to the catalog
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Product'
      responses:
        200:
          description: Product has been created.
    get:
      parameters:
        - in: query
          name: pageNumber
          description: Page number to return
          required: false
          schema:
            type: integer
            example: 1
        - in: query
          name: pageSize
          description: Number of results in the page
          required: false
          schema:
            type: integer
            example: 50
            maximum: 100
      responses:
        200:
          description: This is a list of products in the catalog
          content:
            application/json:
              schema:
                  type: array
                  items:
                    $ref: '#/components/schemas/Product'
  /article:
    get:
      tags:
        - Article
      responses:
        200:
          description: Page of Articles
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Article'
    post:
      description: Add a product to the catalog
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Article'
      responses:
        200:
          description: Product has been created.
        201:
          description: Article has been created
components:
  schemas:
    Product:
      type: object
      required:
        - name
      properties:
        id:
          type: integer
          example: 212
        name:
          type: string
          example: Lemon Water
        discription:
          type: string
          example: "Lemon tasting juice with more water"
        image_title:
          type: string
          example: "mineral-water-lemon-lime"
        image:
          type: string
          example: "https://google.com/?search=lemonwater.png"
    Article:
      type: object
      properties:
        createdDate:
          type: string
          format: date
        tagline:
          type: string
        content:
          type: string
        category:
          type: string
        tags:
          type: array
          items:
            type: string
    responses:
      500ApiError:
        description: This is an unexpected error
        content:
          application/json:
            schema:
              type: object
              properties:
                statusCode:
                  type: string
                  example: 500
                message:
                  type: string
                  example: This is an error
            
            
            
            
            
            
            
            
            
            
                        
                        
                        
                        
                        
                        
                        
                      
