# Generated by Django 5.1.4 on 2024-12-27 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0002_remove_comment_id_comment_main_referance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='user_id',
            field=models.BigIntegerField(default=0),
        ),
    ]
